%% ============================================================
%  gBOLD - CSF lagged cross-correlation:  TWO-STAGE GROUP ANALYSIS
%  ------------------------------------------------------------
%  Fixes the pseudoreplication problem of pooling epochs across
%  participants: here the unit of inference is the PARTICIPANT.
%
%  STAGE 1  (per participant -- ESTIMATION ONLY, no testing)
%     for each epoch, for each lag L:  r = corr(gBOLD, CSF shifted by L)
%     -> Fisher-z transform      z = atanh(r)
%     -> average z across that participant's epochs
%     => ONE z-curve per participant
%
%  STAGE 2  (across participants -- INFERENCE)
%     at each lag: one-sample t-test of the participants' z against 0
%     -> Benjamini-Hochberg FDR across the lags
%     -> mean z transformed back to r (tanh) for plotting
%
%  ONE OR SEVERAL CONDITIONS
%     stageLabels may list one stage set or several. With several, each
%     condition is run through both stages separately and all curves are
%     drawn into ONE figure (e.g. sleep vs. wake control).
%
%  CONVENTION:   r(L) = corr( gBOLD(t), CSF(t + L) )
%     positive lag L  ->  CSF sampled LATER   ->  "CSF follows gBOLD"
%     negative lag L  ->  CSF sampled EARLIER ->  "CSF leads gBOLD"
%  This is the SAME convention as csf_gm_cross_correlation_within_epoch.m,
%  so the two analyses can be compared directly.
%
%  ATTENTION: The axis are flipped in the end to represent the Plots
%  generated by previous studies (HAN et al.). This is not reversing the results this is
%  just a different defintion of what a psoitive Lag means verablly vs.
%  what it does in the code
%
%  Lags never cross an epoch border: every correlation is computed inside
%  one continuous epoch, on the overlapping window only.
%
%  Base MATLAB only - no Statistics Toolbox required.
%  1 TR = 1 volume = 2.5 s.
% ============================================================

%% ---------------- CONFIG ----------------
% Sleep-stage definition(s). Drives ALL folder names.
% Allowed entries: "N2" | "N2_N3" | "N1_N2_N3" | "W"
%   ONE entry   -> single-condition figure, saved under <stage>/within_epoch/group_level
%   TWO or more -> all curves in one figure, saved under multi_stage
% The FIRST entry is treated as the primary condition (it gets the peak
% annotation and is drawn on top).
stageLabels = ["N1_N2_N3", "W"];

% Participants to analyse. [] = every participant found in the CSF folder.
% Otherwise a list of numbers, e.g. [5 8 22 23]
subjects   = [];

% With several conditions: restrict to participants that contribute a
% curve in EVERY condition, so the comparison is within the same people.
% Strongly recommended for the sleep-vs-wake contrast.
matchSubjects = true;

TR         = 2.5;    % seconds per TR / volume
maxLagTR   = 5;      % lags -5..+5 TR  (= -12.5 .. +12.5 s)
alphaFDR   = 0.05;   % FDR level for the Benjamini-Hochberg correction

% How to combine a participant's epochs in Stage 1:
%   "invvar" - weight each epoch by (n_overlap - 3), the inverse variance
%              of a Fisher-z value. Long epochs give more reliable r and
%              therefore count more. RECOMMENDED: epoch lengths here range
%              from 36 to >900 TR, so equal weighting adds a lot of noise.
%   "equal"  - plain unweighted mean across epochs.
epochWeighting = "invvar";

minOverlapTR = 10;   % skip an epoch/lag if fewer samples than this overlap

% What is correlated against the CSF signal.
%   "none"            - the gBOLD signal itself. gBOLD is a STATE (a proxy
%                       for blood volume), the CSF signal is a FLOW, so the
%                       two are not the same kind of quantity.
%   "negderiv"        - the NEGATIVE time derivative of gBOLD, i.e. how fast
%                       blood volume is FALLING. This turns gBOLD into a
%                       flow, so both signals are the same kind of quantity.
%                       Follows Han et al. (2021).
%   "negderiv_thresh" - as "negderiv", but negative values are set to zero,
%                       keeping only the phase in which blood is leaving.
%                       Follows Fultz et al. (2019), whose CSF measurement
%                       can see inflow but not outflow.
gboldTransform = "negderiv";

% Lag axis orientation FOR THE PLOT ONLY. The computation, the console
% table and the saved .mat are ALWAYS in this script's own convention and
% are never touched by this switch.
flipLagAxisForDisplay = false;

saveResults  = true; % write a .mat with all per-participant curves + stats
dpi          = 200;

% ---- roots (note the different capitalisation of the two data roots) ----
csfRoot  = '/Users/Richard/Masterabeit_local/SNORE_CSF_Data/Sleep_Stage_Segmented';
gmRoot   = '/Users/Richard/Masterabeit_local/SNORE_GM_Data/sleep_stage_segmented';
plotRoot = '/Users/Richard/Masterabeit_local/SNORE_Plots/Cross_Correlaltion';

%% ---------------- DERIVED PATHS AND LAGS ----------------
stageLabels = string(stageLabels(:)).';
nCond       = numel(stageLabels);

lagsTR  = -maxLagTR:maxLagTR;      % 1 x nLags
lagsSec = lagsTR * TR;             % native convention, used everywhere
nLags   = numel(lagsTR);

% display-only mirroring of the x-axis (see flipLagAxisForDisplay above)
if flipLagAxisForDisplay
    lagSign = -1;
    lagAxisNote = 'positive = CSF LEADS gBOLD';
    axisTag = '_FlippedAxis';
else
    lagSign = 1;
    lagAxisNote = 'positive = CSF follows gBOLD';
    axisTag = '';
end
lagsPlot = lagsSec * lagSign;

% file-name prefix and human-readable name for the chosen gBOLD transform
switch string(gboldTransform)
    case "none"
        transformTag = '';           transformNote = 'gBOLD';
    case "negderiv"
        transformTag = 'deriv_';     transformNote = '-d(gBOLD)/dt';
    case "negderiv_thresh"
        transformTag = 'derivthr_';  transformNote = '-d(gBOLD)/dt, zero-thresholded';
    otherwise
        error('Unknown gboldTransform "%s".', gboldTransform);
end

% where the figure and the .mat go
if nCond == 1
    outDir  = fullfile(plotRoot, char(stageLabels(1)), 'within_epoch', 'group_level');
    fileTag = char(stageLabels(1));
else
    outDir  = fullfile(plotRoot, 'multi_stage');
    fileTag = char(strjoin(stageLabels, '_vs_'));
end
if ~exist(outDir, 'dir'); mkdir(outDir); end

fprintf('\n================ TWO-STAGE GROUP CROSS-CORRELATION ================\n');
fprintf('Conditions: %s\n', strjoin(stageLabels, ', '));
fprintf('Lags      : %d..%d TR  (%.1f..%.1f s)\n', ...
        lagsTR(1), lagsTR(end), lagsSec(1), lagsSec(end));
fprintf('Weighting : %s\n', epochWeighting);
fprintf('Signal    : %s  vs  CSF\n', transformNote);
fprintf('Plot axis : %s\n', lagAxisNote);
fprintf('Output    : %s\n', outDir);
fprintf('===================================================================\n');

%% =====================================================================
%  STAGE 1 - run for every condition
%  =====================================================================
S1 = cell(1, nCond);
for k = 1:nCond
    S1{k} = stage1ForCondition(stageLabels(k), csfRoot, gmRoot, subjects, ...
                               lagsTR, minOverlapTR, epochWeighting, ...
                               TR, gboldTransform);
end

%% ---- optionally restrict to participants present in ALL conditions ----
if nCond > 1 && matchSubjects
    common = S1{1}.subjIDs;
    for k = 2:nCond
        common = intersect(common, S1{k}.subjIDs);
    end
    fprintf('\nMatching participants across conditions: %d in common (%s)\n', ...
            numel(common), strjoin("P" + string(common), ', '));
    for k = 1:nCond
        dropped = setdiff(S1{k}.subjIDs, common);
        if ~isempty(dropped)
            fprintf('   %-10s drops %s\n', stageLabels(k), ...
                    strjoin("P" + string(dropped), ', '));
        end
        keep            = ismember(S1{k}.subjIDs, common);
        S1{k}.subjIDs   = S1{k}.subjIDs(keep);
        S1{k}.Z         = S1{k}.Z(keep,:);
        S1{k}.nEpUsed   = S1{k}.nEpUsed(keep);
    end
end

%% =====================================================================
%  STAGE 2 - inference, per condition
%  =====================================================================
for k = 1:nCond
    nSubj = numel(S1{k}.subjIDs);
    assert(nSubj >= 2, ...
        'Condition %s: need at least 2 participants for a group test (have %d).', ...
        stageLabels(k), nSubj);

    S2 = stage2(S1{k}.Z, alphaFDR);

    fprintf('\n===== %s : STAGE 2 across participants (n = %d, df = %d) =====\n', ...
            stageLabels(k), nSubj, nSubj-1);
    fprintf('%6s %8s %9s %9s %9s %9s  %s\n', ...
            'lag_TR','lag_s','mean_r','t','p','p_FDR','sig');
    fprintf('%s\n', repmat('-',1,64));
    for j = 1:nLags
        if S2.sigFDR(j); mark = '*'; else; mark = ''; end
        fprintf('%6d %8.2f %9.4f %9.3f %9.4f %9.4f  %s\n', ...
                lagsTR(j), lagsSec(j), S2.meanR(j), S2.tStat(j), ...
                S2.pRaw(j), S2.pAdj(j), mark);
    end
    fprintf('%s\n', repmat('-',1,64));
    [~, iNeg] = min(S2.meanR);
    [~, iPos] = max(S2.meanR);
    fprintf('negative peak: r=%+.3f at %+.1f s (%+d TR), p_FDR=%.4f\n', ...
            S2.meanR(iNeg), lagsSec(iNeg), lagsTR(iNeg), S2.pAdj(iNeg));
    fprintf('positive peak: r=%+.3f at %+.1f s (%+d TR), p_FDR=%.4f\n', ...
            S2.meanR(iPos), lagsSec(iPos), lagsTR(iPos), S2.pAdj(iPos));

    S1{k}.stats = S2;
    S1{k}.nSubj = nSubj;
    S1{k}.iNeg  = iNeg;
    S1{k}.iPos  = iPos;
end

%% =====================================================================
%  GROUP-LEVEL PLOT  (all conditions in one figure)
%  =====================================================================
palette = [0.15 0.35 0.70;      % blue    - primary condition
           0.85 0.33 0.10;      % orange  - control
           0.20 0.60 0.25;      % green
           0.50 0.20 0.60];     % purple

fig = figure('Visible','off', 'Color','w', 'Position',[100 100 900 540]);
hold on;

hCurve = gobjects(1, nCond);        % handles, so the legend order can be set
hFDR   = gobjects(1, nCond);
hBand  = gobjects(1);

% --- SE bands first, so the lines are drawn on top of them ---
for k = nCond:-1:1
    col = palette(mod(k-1, size(palette,1))+1, :);
    st  = S1{k}.stats;
    hb  = fill([lagsPlot, fliplr(lagsPlot)], [st.ciHiR, fliplr(st.ciLoR)], col, ...
               'FaceAlpha', 0.15, 'EdgeColor','none');
    if k == 1
        set(hb, 'DisplayName', '\pm1 SE across participants');
        hBand = hb;
    else
        set(hb, 'HandleVisibility','off');
    end
end

% reference lines - kept out of the legend, otherwise they show as data1/data2
yline(0, 'k-', 'HandleVisibility','off');
xline(0, 'k:', 'HandleVisibility','off');

% --- the curves, primary condition drawn last so it sits on top ---
for k = nCond:-1:1
    col  = palette(mod(k-1, size(palette,1))+1, :);
    st   = S1{k}.stats;
    name = prettyStageName(stageLabels(k));

    hCurve(k) = plot(lagsPlot, st.meanR, '-o', 'Color',col, 'LineWidth',1.8, ...
         'MarkerFaceColor',col, 'MarkerSize',5, ...
         'DisplayName', sprintf('%s  (n = %d)', name, S1{k}.nSubj));

    % every condition gets its own FDR entry, in its own colour
    if any(st.sigFDR)
        hFDR(k) = plot(lagsPlot(st.sigFDR), st.meanR(st.sigFDR), 'o', ...
                  'MarkerEdgeColor',col, 'MarkerFaceColor','none', ...
                  'MarkerSize',11, 'LineWidth',1.5, ...
                  'DisplayName', sprintf('%s  FDR q<%.2f', name, alphaFDR));
    end
end

% --- peak annotation for the PRIMARY condition only ---
%   raw gBOLD  : the NEGATIVE peak is the coupling index used by Han et al.
%   derivative : the POSITIVE peak near lag 0 is the result of interest, so
%                the negative peak is not annotated
st1  = S1{1}.stats;
col1 = palette(1,:);
if string(gboldTransform) == "none"
    iAnn = S1{1}.iNeg;  annName = 'neg. peak';  annMark = 'v';  annAlign = 'top';
else
    iAnn = S1{1}.iPos;  annName = 'peak';       annMark = '^';  annAlign = 'bottom';
end
plot(lagsPlot(iAnn), st1.meanR(iAnn), annMark, 'Color',col1, ...
     'MarkerFaceColor',col1, 'MarkerSize',9, 'HandleVisibility','off');
text(lagsPlot(iAnn), st1.meanR(iAnn), ...
     sprintf('  %s %.1f s, r=%.3f', annName, lagsPlot(iAnn), st1.meanR(iAnn)), ...
     'Color',col1, 'VerticalAlignment',annAlign, 'FontSize',9);

hold off;
xlabel(sprintf('Lag (s)     [ %s ]', lagAxisNote));
ylabel(sprintf('Pearson correlation   (%s vs CSF)', transformNote));
prettyNames = arrayfun(@prettyStageName, stageLabels);
if nCond == 1
    title(sprintf('%s vs CSF cross-correlation  -  %s, two-stage, n = %d', ...
                  transformNote, prettyNames(1), S1{1}.nSubj), 'Interpreter','none');
else
    title(sprintf('%s vs CSF cross-correlation  -  %s (two-stage)', ...
                  transformNote, strjoin(prettyNames, ' vs ')), 'Interpreter','none');
end
xticks(sort(lagsPlot)); xlim([min(lagsPlot) max(lagsPlot)]); grid off;

% legend in a fixed order: primary condition first, SE band last
legHandles = gobjects(0);
for k = 1:nCond
    legHandles(end+1) = hCurve(k);                                  %#ok<SAGROW>
    if isgraphics(hFDR(k)); legHandles(end+1) = hFDR(k); end        %#ok<SAGROW>
end
if isgraphics(hBand); legHandles(end+1) = hBand; end
legend(legHandles, 'Location','northwest', 'Box','off');

if nCond == 1
    outPng = fullfile(outDir, sprintf('group_xcorr_%s%s_twostage_n%d%s.png', ...
                                      transformTag, fileTag, S1{1}.nSubj, axisTag));
else
    outPng = fullfile(outDir, sprintf('group_xcorr_%s%s_twostage%s.png', ...
                                      transformTag, fileTag, axisTag));
end
try
    exportgraphics(fig, outPng, 'Resolution', dpi);
catch
    print(fig, outPng, '-dpng', sprintf('-r%d', dpi));
end
close(fig);
fprintf('\nPlot   : %s\n', outPng);

%% =====================================================================
%  SAVE RESULTS  (one entry per condition)
%  =====================================================================
if saveResults
    results = struct('stage_label',{},'subject_ids',{},'n_subjects',{}, ...
                     'n_epochs_used',{},'lags_TR',{},'lags_s',{}, ...
                     'z_per_subject',{},'r_per_subject',{},'mean_z',{}, ...
                     'se_z',{},'mean_r',{},'ci_lo_r',{},'ci_hi_r',{}, ...
                     't_stat',{},'p_raw',{},'p_fdr',{},'sig_fdr',{}, ...
                     'alpha_fdr',{},'TR',{},'max_lag_TR',{}, ...
                     'epoch_weighting',{},'min_overlap_TR',{}, ...
                     'gbold_transform',{}, ...
                     'matched_subjects',{},'lag_convention',{}, ...
                     'flip_lag_axis_for_display',{},'csf_dir',{},'gm_dir',{}, ...
                     'created',{});
    for k = 1:nCond
        st = S1{k}.stats;
        results(k) = struct( ...
            'stage_label',      stageLabels(k), ...
            'subject_ids',      S1{k}.subjIDs, ...
            'n_subjects',       S1{k}.nSubj, ...
            'n_epochs_used',    S1{k}.nEpUsed, ...
            'lags_TR',          lagsTR, ...
            'lags_s',           lagsSec, ...
            'z_per_subject',    S1{k}.Z, ...
            'r_per_subject',    tanh(S1{k}.Z), ...
            'mean_z',           st.meanZ, ...
            'se_z',             st.seZ, ...
            'mean_r',           st.meanR, ...
            'ci_lo_r',          st.ciLoR, ...
            'ci_hi_r',          st.ciHiR, ...
            't_stat',           st.tStat, ...
            'p_raw',            st.pRaw, ...
            'p_fdr',            st.pAdj, ...
            'sig_fdr',          st.sigFDR, ...
            'alpha_fdr',        alphaFDR, ...
            'TR',               TR, ...
            'max_lag_TR',       maxLagTR, ...
            'epoch_weighting',  string(epochWeighting), ...
            'min_overlap_TR',   minOverlapTR, ...
            'gbold_transform',  string(gboldTransform), ...
            'matched_subjects', (nCond > 1 && matchSubjects), ...
            'lag_convention',   "r(L) = corr( gBOLD(t), CSF(t+L) ); +L = CSF later", ...
            'flip_lag_axis_for_display', flipLagAxisForDisplay, ...
            'csf_dir',          string(S1{k}.csfDir), ...
            'gm_dir',           string(S1{k}.gmDir), ...
            'created',          string(datetime('now')));
    end
    if nCond == 1
        outMat = fullfile(outDir, sprintf('group_xcorr_%s%s_twostage_n%d.mat', ...
                                          transformTag, fileTag, S1{1}.nSubj));
    else
        outMat = fullfile(outDir, sprintf('group_xcorr_%s%s_twostage.mat', ...
                                          transformTag, fileTag));
    end
    % note: no axisTag here - the saved numbers are always in the native
    % convention, regardless of how the figure was drawn
    save(outMat, 'results');
    fprintf('Results: %s\n', outMat);
end
fprintf('\nDone.\n');


%% ======================= CONDITION RUNNERS =======================
function out = stage1ForCondition(stageLabel, csfRoot, gmRoot, subjects, ...
                                  lagsTR, minOverlapTR, epochWeighting, ...
                                  TR, gboldTransform)
    % Stage 1 for ONE stage definition -> one Fisher-z curve per participant.
    csfDir = fullfile(csfRoot, char(stageLabel));
    gmDir  = fullfile(gmRoot,  char(stageLabel));

    D = dir(fullfile(csfDir, sprintf('csf_p*_%s.mat', stageLabel)));
    assert(~isempty(D), 'No csf_p*_%s.mat in %s', stageLabel, csfDir);

    fprintf('\n===== %s : STAGE 1 within participant =====\n', stageLabel);
    fprintf('CSF dir   : %s\n', csfDir);
    fprintf('GM  dir   : %s\n', gmDir);
    fprintf('%-7s %8s %9s %10s   %s\n', 'Subj','#epochs','usedEp','concatTR','status');
    fprintf('%s\n', repmat('-',1,64));

    subjIDs = []; Z = []; nEpUsed = []; seen = [];

    for i = 1:numel(D)
        tok = regexp(D(i).name, 'p(\d+)_', 'tokens', 'once');
        if isempty(tok); continue; end
        N = str2double(tok{1});

        if ~isempty(subjects) && ~ismember(N, subjects); continue; end
        seen(end+1) = N; %#ok<AGROW>

        gmPath = fullfile(gmDir, sprintf('gbold_p%d_%s.mat', N, stageLabel));
        if exist(gmPath, 'file') ~= 2
            fprintf('P%-6d %8s %9s %10s   %s\n', N, '-','-','-','no gBOLD file -> skipped');
            continue
        end

        Cs = load(fullfile(D(i).folder, D(i).name));
        Gs = load(gmPath);

        % load the already-concatenated vectors (no maths here, just loading)
        c = double(loadStageSignal(Cs, D(i).name));   % CSF
        g = double(loadStageSignal(Gs, gmPath));      % gBOLD
        n = min(numel(c), numel(g));
        c = c(1:n); g = g(1:n);

        bounds = epochBounds(Cs.epochs, n);
        checkEpochsMatch(Cs.epochs, Gs.epochs, N);

        [zSubj, nUsed] = subjectZCurve(g, c, bounds, lagsTR, minOverlapTR, ...
                                       epochWeighting, TR, gboldTransform);

        if nUsed == 0
            fprintf('P%-6d %8d %9d %10d   %s\n', N, size(bounds,1), 0, n, ...
                    'no usable epoch -> skipped');
            continue
        end

        subjIDs(end+1) = N;      %#ok<AGROW>
        Z(end+1,:)     = zSubj;  %#ok<AGROW>
        nEpUsed(end+1) = nUsed;  %#ok<AGROW>

        fprintf('P%-6d %8d %9d %10d   %s\n', N, size(bounds,1), nUsed, n, '');
    end

    if ~isempty(subjects)
        for N = setdiff(subjects(:).', seen)
            fprintf('P%-6d %8s %9s %10s   %s\n', N, '-','-','-','no CSF file -> skipped');
        end
    end

    % keep only participants with a complete curve, so n is the same at
    % every lag and the reported df is unambiguous
    if ~isempty(Z)
        bad = any(~isfinite(Z), 2);
        if any(bad)
            warning('%s: dropping %d participant(s) with an incomplete z-curve: %s', ...
                    stageLabel, sum(bad), strjoin("P" + string(subjIDs(bad)), ', '));
            Z(bad,:) = []; subjIDs(bad) = []; nEpUsed(bad) = [];
        end
    end

    fprintf('%s\n', repmat('-',1,64));
    fprintf('Stage 1 done: %d participant(s) contribute a z-curve.\n', numel(subjIDs));

    out = struct('stageLabel',stageLabel, 'csfDir',csfDir, 'gmDir',gmDir, ...
                 'subjIDs',subjIDs, 'Z',Z, 'nEpUsed',nEpUsed);
end

function name = prettyStageName(stageLabel)
    % Readable condition name for figure text.
    %   "W"         -> "Wake"
    %   "N1_N2_N3"  -> "Sleep (N1, N2, N3)"
    %   "N2"        -> "Sleep (N2)"
    % Also removes the underscores, which MATLAB would otherwise render as
    % TeX subscripts in the legend (N1_N2_N3 came out as "N1_N2 3").
    s = string(stageLabel);
    if strcmpi(s, "W")
        name = "Wake";
    else
        parts = split(s, "_");
        name  = "Sleep (" + strjoin(parts.', ", ") + ")";
    end
end

function st = stage2(Z, alphaFDR)
    % Across-participant inference for ONE condition.
    nSubj = size(Z,1);
    st.meanZ = mean(Z, 1);
    st.sdZ   = std(Z, 0, 1);
    st.seZ   = st.sdZ / sqrt(nSubj);
    st.tStat = st.meanZ ./ st.seZ;
    st.pRaw  = tTestP(st.tStat, nSubj - 1);
    [st.sigFDR, st.pAdj] = fdrBH(st.pRaw, alphaFDR);
    st.meanR = tanh(st.meanZ);
    st.ciLoR = tanh(st.meanZ - st.seZ);
    st.ciHiR = tanh(st.meanZ + st.seZ);
end


%% ======================= STAGE 1 HELPERS =======================
function [zSubj, nUsed] = subjectZCurve(g, c, bounds, lagsTR, minOverlapTR, ...
                                        weighting, TR, gboldTransform)
    % One participant -> one Fisher-z value per lag.
    % Every correlation is computed INSIDE one epoch, on the overlapping
    % window only, so a lag never mixes samples across an epoch border.
    nL   = numel(lagsTR);
    acc  = zeros(1, nL);        % sum of  w * z
    wsum = zeros(1, nL);        % sum of  w
    used = false(size(bounds,1), 1);

    for e = 1:size(bounds,1)
        a = bounds(e,1); b = bounds(e,2);
        ge = g(a:b); ce = c(a:b);

        % optional transform of gBOLD, applied INSIDE the epoch so that a
        % derivative never spans a concatenation join
        [ge, ce] = applyGboldTransform(ge, ce, gboldTransform, TR);
        if numel(ge) < minOverlapTR; continue; end

        for k = 1:nL
            L = lagsTR(k);
            [x, y] = shiftPair(ge, ce, L);      % <-- the lag mechanics
            nOv = numel(x);
            if nOv < minOverlapTR; continue; end

            r = pear(x, y);
            if ~isfinite(r); continue; end
            r = min(max(r, -0.999999), 0.999999);   % keep atanh finite
            z = atanh(r);

            switch string(weighting)
                case "invvar", w = max(nOv - 3, 1);  % 1/var of a Fisher-z
                otherwise,     w = 1;                % "equal"
            end
            acc(k)  = acc(k)  + w*z;
            wsum(k) = wsum(k) + w;
            used(e) = true;
        end
    end

    zSubj = acc ./ wsum;            % weighted mean Fisher-z per lag
    zSubj(wsum == 0) = NaN;
    nUsed = sum(used);
end

function [ge, ce] = applyGboldTransform(ge, ce, mode, TR)
    % Turns the gBOLD STATE into a FLOW, so that it is the same kind of
    % quantity as the CSF inflow signal. Both series are returned, because
    % they must always be trimmed identically (see below).
    switch string(mode)
        case "none"
            return                      % leave both series untouched

        case {"negderiv", "negderiv_thresh"}
            % CENTRED difference: gradient(x,TR) uses the sample BEFORE and
            % the sample AFTER, so the result is timed exactly on the current
            % volume. A backward difference (diff) describes the change
            % between two volumes and therefore belongs half a volume earlier;
            % using it would bias every lag by TR/2 = 1.25 s.
            ge = -gradient(ge, TR);     % positive = blood volume FALLING

            if string(mode) == "negderiv_thresh"
                % keep only the phase in which blood is leaving; must come
                % AFTER the sign flip, or the wrong half survives
                ge = max(ge, 0);
            end

            % gradient falls back to a ONE-SIDED difference at the first and
            % last sample, which carries exactly the timing bias avoided
            % above. Drop those two samples - and drop the SAME samples from
            % the CSF signal, otherwise the two series shift against each
            % other by one volume without any error being raised.
            ge = ge(2:end-1);
            ce = ce(2:end-1);

        otherwise
            error('Unknown gboldTransform "%s".', mode);
    end
end

function [x, y] = shiftPair(g, c, L)
    % THE LAG MECHANICS.  Convention: r(L) = corr( g(t), c(t+L) ).
    % No padding and no wrapping: we simply take the window where both
    % signals exist after sliding CSF by L samples. Both outputs have
    % length ne-|L| and are aligned element by element.
    ne = numel(g);
    if L >= 0
        % CSF sampled LATER: pair g(1..ne-L) with c(1+L..ne)
        x = g(1:ne-L);        y = c(1+L:ne);
    else
        % CSF sampled EARLIER: pair g(1+|L|..ne) with c(1..ne-|L|)
        m = -L;
        x = g(1+m:ne);        y = c(1:ne-m);
    end
end

function bounds = epochBounds(epochs, nMax)
    % Start/end index of each epoch inside the concatenated signal,
    % clipped to the length actually available in both files.
    bounds = zeros(numel(epochs), 2);
    for e = 1:numel(epochs)
        bounds(e,:) = [epochs(e).concat_start, min(epochs(e).concat_end, nMax)];
    end
    bounds = bounds(bounds(:,2) >= bounds(:,1), :);
end

function checkEpochsMatch(epC, epG, N)
    % CSF and gBOLD epochs must describe the same stretches of the night.
    if numel(epC) ~= numel(epG)
        warning('P%d: CSF has %d epochs but gBOLD has %d - pairing by index.', ...
                N, numel(epC), numel(epG));
        return
    end
    sC = [epC.src_start_TR]; eC = [epC.src_end_TR];
    sG = [epG.src_start_TR]; eG = [epG.src_end_TR];
    if ~isequal(sC, sG) || ~isequal(eC, eG)
        warning('P%d: CSF and gBOLD epoch boundaries differ - check the segmentation.', N);
    end
end

function v = loadStageSignal(S, src)
    % PURE LOADER - does no maths and concatenates nothing.
    % The concatenation already happened in segment_stable_sleep_epochs.m,
    % which stored the finished vector under one of two names:
    %   stage_signal  (current script)
    %   n2_signal     (older _N2 script, still used by the N2 folder)
    % This just picks whichever name is present.
    % The epoch borders inside that vector are recovered separately by
    % epochBounds(), and subjectZCurve() correlates strictly within them.
    if     isfield(S, 'stage_signal'); v = S.stage_signal(:);
    elseif isfield(S, 'n2_signal');    v = S.n2_signal(:);
    else
        error('Neither "stage_signal" nor "n2_signal" found in %s', char(src));
    end
end

function r = pear(x, y)
    % Pearson correlation, base MATLAB (no toolbox).
    x = x(:); y = y(:); nn = numel(x);
    dx = x - sum(x)/nn;  dy = y - sum(y)/nn;
    d  = sqrt(sum(dx.^2) * sum(dy.^2));
    if d == 0, r = NaN; else, r = sum(dx.*dy) / d; end
end


%% ======================= STAGE 2 HELPERS =======================
function p = tTestP(t, df)
    % Two-sided p-value of a t statistic, without the Statistics Toolbox.
    % Uses the identity  P(|T|>t) = I_{df/(df+t^2)}(df/2, 1/2),
    % where I is the regularised incomplete beta function (betainc).
    p = betainc(df ./ (df + t.^2), df/2, 0.5);
    p(~isfinite(t)) = NaN;
end

function [sig, pAdj] = fdrBH(p, q)
    % Benjamini-Hochberg FDR. Returns the reject mask at level q and the
    % BH-adjusted p-values (monotone, capped at 1).
    p = p(:).';  m = numel(p);
    [ps, ord] = sort(p);

    % reject the k smallest p-values, where k is the largest index with
    % p(k) <= q*k/m
    below = find(ps <= q * (1:m) / m, 1, 'last');
    sig = false(1, m);
    if ~isempty(below); sig(ord(1:below)) = true; end

    % adjusted p-values: step-up, enforced monotone from the largest down
    adjS = ps .* m ./ (1:m);
    for k = m-1:-1:1
        adjS(k) = min(adjS(k), adjS(k+1));
    end
    pAdj = zeros(1, m);
    pAdj(ord) = min(adjS, 1);
end
